# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET http://localhost:7071/api/invoice

###

GET http://localhost:7071/api/invoice/00005

###

POST http://localhost:7071/api/invoice
Content-Type: application/json
{ "id": "000111", "dt": "2025-02-20T18:15:48.6421246Z", "customerID": "CUST-1", "amount": 500 }

###

PUT http://localhost:7071/api/invoice
Content-Type: application/json
{ "id": "00002", "dt": "2025-02-20T18:15:48.6421246Z",
  "customerID": "CUST-1", "amount": 9999 }

###

DELETE http://localhost:7071/api/invoice/00002
